name: WhiteSource CI integration
description: automation for executing the WS agent in an organization with configuration files

on:
  pull_request:
    branches: [ $default-branch ]

runs:
    using: "composite" 
    steps:
  
    - name: Downloading the WS config file
      # Download the project config file repository.
      run: |
        git clone https://"$WHITESOURCE_GH_PAT"@github.com/"$WHITESOURCE_CONFIG_REPO" |& tee repo.txt
        repoName=$(cat repo.txt | grep Cloning | cut -d"'" -f2) 
        cp ./$repoName/"$WHITESOURCE_PRODUCT_NAME"/"$WHITESOURCE_PROJECT_NAME"/wss-generated-file-CI.config .
      shell: bash 
      
    - name: Install project prerequisites 
      # install dependencies based on the technology in use 
      run: |
         sudo apt update
         if grep -q npm wss-generated-file-CI.config; then sudo apt install npm; fi
         if grep -q gradle wss-generated-file-CI.config; then sudo apt install gradle; fi
         if grep -q hex wss-generated-file-CI.config; then sudo apt install elixir; fi
         if grep -q python wss-generated-file-CI.config; then sudo apt install virtualenv; fi
         if grep -q maven wss-generated-file-CI.config; then sudo apt install maven; fi
         if grep -q ant wss-generated-file-CI.config; then sudo apt-get install ant; fi
         if grep -q bower wss-generated-file-CI.config; then sudo npm install -g bower; fi
      shell: bash
      
    - name: Downloading the WS agent 
      run: curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
      shell: bash
         
    - name: Execute the scan
      run: java -jar wss-unified-agent.jar -c wss-generated-file-CI.config -apiKey "$WHITESOURCE_API_KEY" -logLevel debug
      shell: bash
      env:
         NPM_TOKEN: "$WHITESOURCE_NPM_TOKEN"

         
     # print the policy rejection summary to know what needs to be done 
    - name: Print the Policy Rejection Summary
      run: if [ -f ./whitesource/policyRejectionSummary.json ] && cat ./whitesource/policyRejectionSummary.json
      shell: bash
